register:
  path: /api/auth/register
  controller: App\Controller\AuthController::register
  methods: POST

login:
  path: /api/auth/login
  controller: App\Controller\AuthController::login
  methods: POST

create_product:
  path: /api/products
  controller: App\Controller\ProductController::store
  methods: POST

update_product:
  path: /api/products/{id}
  controller: App\Controller\ProductController::update
  methods: PUT